<?php

namespace Source\App\Model;

use Magento\Framework\Model\AbstractModel;
use Source\App\Model\Resource\Post as PostResource;

class Post extends AbstractModel
{

    protected function _construct()
    {
        $this->_init(PostResource::class);
        parent::_construct(); // TODO: Change the autogenerated stub
    }
}
